import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import ClientLayout from "./components/ClientLayout";
import { ChatProvider } from "./context/ChatContext";
const inter = Inter({ subsets: ["latin"] });
 
const montserrat = Montserrat({ subsets: ["latin"] });
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ChatProvider>
          <ClientLayout>{children}</ClientLayout>
        </ChatProvider>
      </body>
    </html>
  );
}
